site_name: Developer Docs
site_url: https://docs.vipm.io
repo_name: vipm-io/docs
edit_uri: edit/main/docs/
repo_url: https://github.com/vipm-io/docs

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    edit: material/file-edit-outline
    repo: fontawesome/brands/github

  palette:
    primary: white
    accent: deep orange

  custom_dir: overrides

  font:
    text: Roboto

extra:
  homepage: https://vipm.io
  social:
    - icon: custom/vipm
      link: https://vipm.io
      name: vipm.io
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vipm
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/showcase/vi-package-manager/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/uyXwAz4B63

hooks:
  - hooks.py

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.snippets:
      base_path: docs/.snippets
      check_paths: true

plugins:
  - redirects:
      redirect_maps:
        'report-a-problem.md': 'support.md'

nav:
  - Home: index.md
  - VIPM 2026Q1 Preview 3: preview.md
  - vipm.toml (Preview):
    - vipm-toml/index.md
    - vipm-toml/getting-started.md
  - VIPM Edition Comparison: vipm-editions-comparison.md
  - Building packages:
    - building-packages/index.md
    - building-packages/building-vi-packages-that-depend-on-other-software.md
    - building-packages/vi-packages-build-templates.md
  - Publishing packages:
    - publishing-packages/index.md
  - CLI:
    - cli/index.md
    - cli/getting-started.md
    - cli/command-reference.md
    - cli/docker.md
    - cli/github-actions.md
  - Linux:
    - linux/index.md
    - linux/ubuntu.md
    - linux/VIPM Linux Crash on Package Installation - Permission Fix.md
  - Security: security/index.md
  - Release notes:
    - release-notes/index.md
    - release-notes/2025.3.1.md
    - release-notes/2025.3.md
    - release-notes/2024.3.md
    - release-notes/2024.1.md
    - release-notes/2023.3.md
    - release-notes/2023.1.md
  - Support: support.md
  - Troubleshooting:
    - troubleshooting/index.md
    - troubleshooting/are-vipms-online-services-down.md

